// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUiH3FpnFRzRzz1OrM7sPhMPVZ0qrHzSI',
    appId: '1:406517659723:web:ac6c0d536866b5e18335ce',
    messagingSenderId: '406517659723',
    projectId: 'fantacyapp-e7486',
    authDomain: 'fantacyapp-e7486.firebaseapp.com',
    storageBucket: 'fantacyapp-e7486.firebasestorage.app',
    measurementId: 'G-KH7NDCGFE3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBII76EI-iaL3dieU8e5klP7tDxEnL7w28',
    appId: '1:406517659723:android:03a0bcd335e9e1ca8335ce',
    messagingSenderId: '406517659723',
    projectId: 'fantacyapp-e7486',
    storageBucket: 'fantacyapp-e7486.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBApvdKRjlkbj6Qz7VIAuFN7C04xj7SDA',
    appId: '1:406517659723:ios:d53af8aa74bb6cf78335ce',
    messagingSenderId: '406517659723',
    projectId: 'fantacyapp-e7486',
    storageBucket: 'fantacyapp-e7486.firebasestorage.app',
    iosClientId: '406517659723-o6qh6d233nq7gkhpb2uas6jt1o8htflf.apps.googleusercontent.com',
    iosBundleId: 'com.example.fantaqcyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBApvdKRjlkbj6Qz7VIAuFN7C04xj7SDA',
    appId: '1:406517659723:ios:d53af8aa74bb6cf78335ce',
    messagingSenderId: '406517659723',
    projectId: 'fantacyapp-e7486',
    storageBucket: 'fantacyapp-e7486.firebasestorage.app',
    iosClientId: '406517659723-o6qh6d233nq7gkhpb2uas6jt1o8htflf.apps.googleusercontent.com',
    iosBundleId: 'com.example.fantaqcyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUiH3FpnFRzRzz1OrM7sPhMPVZ0qrHzSI',
    appId: '1:406517659723:web:f5f01f97fca34da38335ce',
    messagingSenderId: '406517659723',
    projectId: 'fantacyapp-e7486',
    authDomain: 'fantacyapp-e7486.firebaseapp.com',
    storageBucket: 'fantacyapp-e7486.firebasestorage.app',
    measurementId: 'G-S5DW11GN5D',
  );
}
